version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./cache:/data
  restapi:
    build:
      context: ./docker-djangoapi
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./docker-djangoapi:/restapi
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_PORT=6379
    depends_on:
      - db
      - cache
  vueui:
    build:
      context: ./docker-vueui
      dockerfile: Dockerfile
    command: npm run serve
    volumes:
      - ./docker-vueui:/usr/src/app/docker-vueui
      - /usr/src/app/docker-vueui/node_modules
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_URL=http://172.20.76.31:8000
    depends_on:
      - restapi